### ISSUE TITLE
multi-season occupancy?

### ISSUE THREAD

**Issue by cperk** [kenkellner/ubms#45]
Hi!

Your package looks awesome! I'm excited to try it but couldn't find any code examples on how to do multi-season occupancy (non-stacked). Is this possible with ubms and if so do you have a code example I could try? If not, do you have plans to add this feature soon?

Thank you!

-Carrie

**Comment by kenkellner** [comment]
Hi,

The `stan_colext` function can be used for multi-season occupancy modeling. There's a short example if you look at `?stan_colext`. If you want more info, such as how to construct the input `unmarkedFrame`, look at `?unmarkedMultFrame` as well as the dynamic occupancy help files and vignettes for `colext` in the unmarked package, since `stan_colext` is mean to be similar.

Ken

**Comment by cperk** [comment]
Ok thanks! I’ll try it. I noticed another issue you’re working on is making
it possible to specify our own priors. Is that ready to go, and if so is
there example code for it?

**Comment by kenkellner** [comment]
It's not ready yet. Keep an eye on that issue, when it's closed it will be available (in the dev version at least). My current plans for custom priors are pretty simple - if you anticipate needing complicated priors, you're probably better off fitting a custom model in JAGS or Stan.

**Comment by cperk** [comment]
Ok i understand. It appears the stocc package allows full customization of priors, is that correct?

**Comment by cperk** [comment]
Also, is it possible to adapt any of these (ubms, stocc) for a dynamic single-visit occupancy model? I have many years of data but only 1 visit per year.

**Comment by kenkellner** [comment]
stocc does allow some prior customization, but not  to the degree that JAGS would allow. Also, it fits single-season spatial occupancy models only, so I'm not sure it fits your requirements. 

Unfortunately ubms (and stocc, as far as I know) do not support single-visit models. I'm not aware of an R package that does. It looks like Peach et al. 2017 includes JAGS code for the single-visit dynamic model in the supplement so that might be a good starting point.
